micronaut.application.name: $RIT_PARAMETER_APPLICATION_NAME
environment: Dev

# Tracing
tracing:
  jaeger:
    enabled: ${JAEGER_ENABLE:`true`}
    sender:
      agentHost: ${JAEGER_AGENT_HOST:`localhost`}
      agentPort: ${JAEGER_AGENT_PORT:`6831`}
    sampler:
      probability: 1