apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: vault-issuer
    cert-manager.io/common-name: ${{gwIngressHost}}
    kubernetes.io/tls-acme: "true"
  name: $RIT_PARAMETER_APPLICATION_NAME-grpc-gw-ingress
  namespace: eks-default-namespace
spec:
  rules:
  - host: ${{gwIngressHost}}
    http:
      paths:
      - backend:
          serviceName: $RIT_PARAMETER_APPLICATION_NAME-grpc-gw-service
          servicePort: http
  tls:
    - hosts:
      - ${{gwIngressHost}}
      secretName: ${{gwIngressHost}}
