apiVersion: v1
kind: Service
metadata:
  name: $RIT_PARAMETER_APPLICATION_NAME-grpc-gw-service
  labels:
    k8s-app: $RIT_PARAMETER_APPLICATION_NAME-grpc-gw
  namespace: eks-default-namespace
spec:
  selector:
    k8s-app: $RIT_PARAMETER_APPLICATION_NAME-grpc-gw
  ports:
  - port: 8081
    targetPort: 8081
    name: http