version: "3.8"
services:

  app:
    build:
      context: build/libs
      dockerfile: ../../Dockerfile
      network: host
      args:
        HTTPS_PROXY: http://proxyad.itau:8443
        HTTP_PROXY: http://proxyad.itau:8080
        NO_PROXY: "*.localhost, *.corp1.rc.itau, *.rc.itau, *.itau.corp.ihf, *.corp.ihf, *.itau, *.corp.bba.com, *.cloud.ihf"
    ports:
      - 8080:8080
      - 50051:50051
    environment:
      APP_NAME: $RIT_PARAMETER_APPLICATION_NAME
      JAEGER_AGENT_HOST: jaeger
    depends_on:
      - "jaeger"

  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686

