version: "3.8"
services:
  app-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
      network: host
      args:
        HTTPS_PROXY: http://proxyad.itau:8443
        HTTP_PROXY: http://proxyad.itau:8080
        NO_PROXY: "*.localhost, *.corp1.rc.itau, *.rc.itau, *.itau.corp.ihf, *.corp.ihf, *.itau, *.corp.bba.com, *.cloud.ihf"
    ports:
      - 8081:8081
    environment: 
      GRPC_SERVER_ENDPOINT: app:50051
      GATEWAY_NAME: $RIT_PARAMETER_APPLICATION_NAME-grpc-rest-gw
      APP_NAME: $RIT_PARAMETER_APPLICATION_NAME-grpc-gw
      JAEGER_AGENT_HOST: jaeger
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    depends_on:
      - "jaeger"
