datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/mysqldb`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${JDBC_USER:mysqluser}
    password: ${JDBC_PASSWORD:mysqlpassword}
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa:
  default:
    entity-scan:
      packages: 'example.micronaut.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true      